### PR TITLE
refactor tests to use mongo server and add incrementing of totalDonated

### PR DESCRIPTION
**Pull request by joelwass**

### CODE REVIEW

**Review by stripedpajamas — APPROVED** [review]
Fresh testssssss 🥰🥰🥰

**Comment by stripedpajamas** [comment]
Significant coverage drop tho 🧐😔

**Comment by joelwass** [comment]
> Significant coverage drop tho 🧐😔

probably cause i removed testing of "close" and "connect" since those are intrinsically tested, wdyt

**Comment by stripedpajamas** [comment]
> > Significant coverage drop tho 🧐😔
> 
> probably cause i removed testing of "close" and "connect" since those are intrinsically tested, wdyt

if they get called during tests they're considered covered. I'm guessing there are some branches uncovered?

**Comment by joelwass** [comment]
> > > Significant coverage drop tho 🧐😔
> > 
> > 
> > probably cause i removed testing of "close" and "connect" since those are intrinsically tested, wdyt
> 
> if they get called during tests they're considered covered. I'm guessing there are some branches uncovered?

yea this makes no sense because i'm calling the methods in my tests, then verifying that they in fact modify our db as they should

i'm going to merge this so that org distro's are fixed going forward and we can look at why test coverage isn't being picked up on tuesday

**Pull request merged**
